/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnMapRouteImport } from './routes/learn.map'
import { Route as LearnCompletedRouteImport } from './routes/learn.completed'

const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnMapRoute = LearnMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCompletedRoute = LearnCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/parents': typeof ParentsRoute
  '/learn/completed': typeof LearnCompletedRoute
  '/learn/map': typeof LearnMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/parents': typeof ParentsRoute
  '/learn/completed': typeof LearnCompletedRoute
  '/learn/map': typeof LearnMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/parents': typeof ParentsRoute
  '/learn/completed': typeof LearnCompletedRoute
  '/learn/map': typeof LearnMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn' | '/parents' | '/learn/completed' | '/learn/map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/parents' | '/learn/completed' | '/learn/map'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/parents'
    | '/learn/completed'
    | '/learn/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRouteWithChildren
  ParentsRoute: typeof ParentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/map': {
      id: '/learn/map'
      path: '/map'
      fullPath: '/learn/map'
      preLoaderRoute: typeof LearnMapRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/completed': {
      id: '/learn/completed'
      path: '/completed'
      fullPath: '/learn/completed'
      preLoaderRoute: typeof LearnCompletedRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnCompletedRoute: typeof LearnCompletedRoute
  LearnMapRoute: typeof LearnMapRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCompletedRoute: LearnCompletedRoute,
  LearnMapRoute: LearnMapRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRouteWithChildren,
  ParentsRoute: ParentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
